<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
		<PackageReference Include="TngTech.ArchUnitNET" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Architecture.Testing\Architecture.Testing.csproj" />
		<ProjectReference Include="..\..\src\ValueTypes\ValueTypes.csproj" />
	</ItemGroup>

</Project>
